# Utiliser une image Node.js comme image de base
FROM node:14

# Créer un répertoire pour l'application
WORKDIR /usr/src/app

# Copier le package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste du code de l'application
COPY . .

# Exposer le port
EXPOSE 3000

# Démarrer l'application
CMD ["node", "app.js"]